camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  database:
    type: h2
# data source config
# via browser http://localhost:8080/h2-console
# via jdbc jdbc:h2:tcp://localhost:9092/mem:camunda
spring:
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:camunda
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8081

spring.quartz:
  job-store-type: jdbc

spring.quartz.properties.org.quartz.jobStore:
  isClustered: true

spring.quartz.properties.org.quartz.scheduler:
  instanceId: AUTO
